export const TECH = [
  { name: "CSS", color: "#264de4", src: "/tech/css.png" },
  { name: "HTML", color: "#e34c26", src: "/tech/html.png" },
  { name: "JAVASCRIPT", color: "#f7df1e", src: "/tech/javascript.png" },
  { name: "REACT", color: "#61dafb", src: "/tech/reactjs.png" },
  { name: "NEXTJS", color: "#7d8591", src: "/tech/nextjs.png" },
  { name: "NODEJS", color: "#8CC84B", src: "/tech/nodejs.png" },
  { name: "EXPRESSJS", color: "#c9c9c9", src: "/tech/express.png" },
  { name: "TAILWINDCSS", color: "#00afcd", src: "/tech/tailwind.png" },
  { name: "MONGODB", color: "#81c784", src: "/tech/mongodb.png" },
  { name: "POSTGRESQL", color: "#34a3f2", src: "/tech/postgresql.png" },
  { name: "THREEJS", color: "#7d8591", src: "/tech/threejs.png" },
  { name: "GITHUB", color: "#7d8591", src: "/tech/github.png" },
];

export const navLinks = [
  { name: "ABOUT ME", src: "#about-me" },
  { name: "SKILLS", src: "#skills" },
  { name: "PROJECTS", src: "#projects" },
  { name: "EXPERIENCE", src: "#experience" },
  { name: "GET IN TOUCH", src: "#get-in-touch" },
];
export const projects = [
  {
    title: "Bloggin'",
    link: "https://bloggin32.vercel.app",
    desc: "Bloggin' is a modern, feature-rich platform that empowers users to create, share, and explore stories. Whether publishing journals, insightful articles, or creative content, Bloggin’ provides a seamless and engaging experience. With secure authentication, a sleek UI, and community features, Bloggin’ ensures your voice reaches the right audience while keeping accounts safe.",
    github: "https://github.com/Mahesh2-3/Bloggin",
    img: "/Projects/bloggin.png",
    tech: {
      frontend: {
        framework: ["react", "react-dom", "react-router-dom"],
        stateManagement: ["@reduxjs/toolkit", "react-redux"],
        uiLibraries: [
          "@mui/material",
          "@heroicons/react",
          "lucide-react",
          "react-icons",
        ],
        styling: [
          "tailwindcss",
          "@tailwindcss/typography",
          "@tailwindcss/vite",
          "@emotion/react",
          "@emotion/styled",
        ],
        formHandling: ["react-hook-form", "react-quill"],
        animations: ["gsap", "gasp", "ogl"],
        httpRequests: ["axios"],
      },
      backend: {
        framework: ["express"],
        authentication: [
          "jsonwebtoken",
          "passport",
          "passport-google-oauth20",
          "bcrypt",
          "bcryptjs",
          "express-session",
          "cookie-parser",
        ],
        database: [
          "mongoose",
          "@prisma/client",
          "sequelize",
          "pg",
          "pg-hstore",
        ],
        fileHandling: ["multer", "cloudinary"],
        email: ["nodemailer"],
        security: ["cors", "dotenv"],
      },
      devTools: {
        frontend: ["vite", "@vitejs/plugin-react"],
        eslint: [
          "eslint",
          "@eslint/js",
          "eslint-plugin-react-hooks",
          "eslint-plugin-react-refresh",
          "globals",
        ],
        typescriptSupport: ["@types/react", "@types/react-dom"],
        ormTools: ["prisma"],
      },
    },
  },
  {
    title: "Todo2.0",
    link: "https://todo2-0new.vercel.app/",
    desc: "This is the latest version of our To-Do platform, designed to help you stay organized. You can manage tasks, schedule activities, and maintain a diary — all in one place. The platform is secured with a reliable login system, and you can report issues for quick support.",
    github: "https://github.com/Mahesh2-3/Todo2.0",
    img: "/Projects/todo.png",
    tech: {
      frontend: {
        framework: ["next", "react", "react-dom", "react-router-dom"],
        uiLibraries: [
          "@mui/material",
          "react-icons",
          "react-responsive",
          "react-toastify",
          "react-circular-menu",
          "react-circular-progressbar",
          "react-datepicker",
        ],
        styling: ["tailwindcss", "@tailwindcss/vite"],
        formHandling: ["react-hook-form"],
        animations: ["framer-motion"],
        "3dGraphics": ["three", "@react-three/fiber"],
        httpRequests: ["axios", "node-fetch"],
      },
      backend: {
        database: ["mongoose"],
        authentication: ["jsonwebtoken", "bcryptjs"],
        email: ["emailjs-com"],
      },
      devTools: {
        buildTools: ["vite", "@vitejs/plugin-react"],
        linting: [
          "eslint",
          "eslint-config-next",
          "@eslint/js",
          "@eslint/eslintrc",
          "eslint-plugin-react-hooks",
          "eslint-plugin-react-refresh",
          "globals",
        ],
        stylingTools: ["tailwind", "@tailwindcss/postcss"],
        typescriptSupport: ["@types/react", "@types/react-dom"],
      },
    },
  },
  {
    title: "AOT - Game",
    link: "https://aot-game32.vercel.app",
    desc: "An Advanced JavaScript-based fan game inspired by the Attack on Titan anime, where you can shoot enemies with a cannonball to protect your base. The game features multiple difficulty modes, score tracking, pause and exit controls, and ends when an enemy successfully breaches your border.",
    github: "https://github.com/Mahesh2-3/AOT-Game",
    img: "/Projects/aot.jpg",
    tech: ["HTML", "CSS", "JavaScript"],
  },
  {
    title: "Netflix Clone",
    link: "https://netflix-clone-32.vercel.app",
    desc: "A responsive Netflix Clone built using HTML and Tailwind CSS. This project replicates the sleek UI of Netflix with modern design, including a homepage, sections, and hover effects. The layout is responsive, ensuring a smooth experience across devices. I created this project early in my journey to improve UI skills, focusing on design and responsiveness using Tailwind CSS.",
    github: "https://github.com/Mahesh2-3/NetflixClone",
    img: "/Projects/netflix.png",
    tech: ["HTML", "TailwindCSS"],
  },
];

export const Experiences = [
  {
    role: "Frontend Developer - Intern",
    company: "Digital Guruji",
    img: "/digitalGuruji.png",
    duration: "MAY 2025 - OCT 2025",
    points: [
      "Developed and maintained code for in-house and client websites using HTML, CSS, and JavaScript.",
      "Built responsive and visually appealing user interfaces.",
      "Created coding tools such as a CSS Clip-Path Generator, Glassmorphism Generator, and JavaScript Obfuscator.",
      "Improved tools iteratively based on user testing.",
      "Handled entire frontend architecture and code quality.",
    ],
  },
];
